wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1654132965
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 45
      - 53
      - 54
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 45
      - 53
      - 54
      - 55
      3:
      - 13
      4: 3.7.13
      5: 0.12.17
      8:
      - 5
accumulation_steps:
  desc: null
  value: null
amp_opt_level:
  desc: null
  value: null
batch_size:
  desc: null
  value: null
cache_mode:
  desc: null
  value: part
cfg:
  desc: null
  value: ./config/swint_jax.yaml
data_path:
  desc: null
  value: null
disable_amp:
  desc: null
  value: false
eval:
  desc: null
  value: false
name:
  desc: null
  value: swint_jax
opts:
  desc: null
  value: null
pretrained:
  desc: null
  value: null
resume:
  desc: null
  value: null
seed:
  desc: null
  value: 304
tag:
  desc: null
  value: null
throughput:
  desc: null
  value: false
use_checkpoint:
  desc: null
  value: false
zip:
  desc: null
  value: false
